// Code generated by go run ./internal/generate; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	prov "github.com/xavidop/mamori/providers/aws"
	"github.com/yaronf/mamori-resolver/serve"
)

func main() {
	if err := serve.ServeWith(serve.Options{
		Name: "aws",
	}, prov.NewSecretsManager(), prov.NewParameterStore(), prov.NewAppConfig()); err != nil {
		fmt.Fprintf(os.Stderr, "mamori-provider-aws: %v\n", err)
		os.Exit(1)
	}
}
