// Code generated by go run ./internal/generate; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	_ "github.com/xavidop/mamori/providers/aws"
	"github.com/yaronf/mamori-resolver/serve"
)

func main() {
	if err := serve.ServeRegistered(serve.Options{Name: "aws"}); err != nil {
		fmt.Fprintf(os.Stderr, "mamori-provider-aws: %v\n", err)
		os.Exit(1)
	}
}
