// Command generate writes cmd/mamori-provider-*/main.go from providers.manifest.json.
//
//	go generate .
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type manifest struct {
	Providers []provider `json:"providers"`
}

type provider struct {
	Name   string `json:"name"`
	Import string `json:"import"`
}

func main() {
	root, err := findRoot()
	if err != nil {
		fatal(err)
	}

	raw, err := os.ReadFile(filepath.Join(root, "providers.manifest.json"))
	if err != nil {
		fatal(err)
	}
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		fatal(err)
	}
	if len(m.Providers) == 0 {
		fatal(fmt.Errorf("manifest: no providers"))
	}

	tmpl := template.Must(template.New("main").Parse(mainTmpl))
	for _, p := range m.Providers {
		if p.Name == "" || p.Import == "" {
			fatal(fmt.Errorf("provider: name and import are required"))
		}
		dir := filepath.Join(root, "cmd", "mamori-provider-"+p.Name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fatal(err)
		}
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, p); err != nil {
			fatal(err)
		}
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			fatal(fmt.Errorf("%s: format: %w\n%s", p.Name, err, buf.String()))
		}
		out := filepath.Join(dir, "main.go")
		if err := os.WriteFile(out, formatted, 0o644); err != nil {
			fatal(err)
		}
		fmt.Println("wrote", out)

		gomod := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(gomod); os.IsNotExist(err) {
			if err := os.WriteFile(gomod, []byte(goModTemplate(p)), 0o644); err != nil {
				fatal(err)
			}
			fmt.Println("wrote", gomod, "(run go mod tidy in that dir)")
		}
	}
}

func goModTemplate(p provider) string {
	provPath := strings.TrimPrefix(p.Import, "github.com/xavidop/mamori/")
	return fmt.Sprintf(`module github.com/yaronf/secret-resolver/cmd/mamori-provider-%s

go 1.26.7

require (
	%s v0.0.0
	github.com/yaronf/secret-resolver/serve v0.0.0
)

replace github.com/yaronf/secret-resolver => ../../

replace github.com/yaronf/secret-resolver/serve => ../../serve

replace github.com/xavidop/mamori => ../../../mamori.git

replace %s => ../../../mamori.git/%s
`, p.Name, p.Import, p.Import, provPath)
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "providers.manifest.json")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("providers.manifest.json not found walking up from %s", dir)
		}
		dir = parent
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate:", err)
	os.Exit(1)
}

const mainTmpl = `// Code generated by go run ./internal/generate; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	_ "{{.Import}}"
	"github.com/yaronf/secret-resolver/serve"
)

func main() {
	if err := serve.ServeRegistered(serve.Options{Name: "{{.Name}}"}); err != nil {
		fmt.Fprintf(os.Stderr, "mamori-provider-{{.Name}}: %v\n", err)
		os.Exit(1)
	}
}
`
